import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { buildBillingLedger, type ServerPayment } from "../shared/server-billing";
import { sortPaymentPayload, verifyPaymentSignature } from "../server/payment-signature";
const base: ServerPayment = { orderId:"baseline", planId:"starter",billingMode:"mensual",amountUsd:60,
 paymentStatus:"paid",createdAt:"2026-08-10T12:00:00.000Z",updatedAt:"2026-08-10T12:00:00.000Z",dueAt:"2026-08-10T12:00:00.000Z" };
const payment = (amount:number, id="one", status="finished"): ServerPayment => ({...base,orderId:id,paymentId:id,dueAt:undefined,
 amountUsd:amount,paymentStatus:status,createdAt:"2026-09-26T20:35:00.000Z",updatedAt:"2026-09-26T20:35:00.000Z",paidAt:"2026-09-26T20:35:00.000Z"});
const now = new Date("2026-09-27T05:00:00Z");
for (const [amount,coverage] of [[60,"2026-09-10"],[120,"2026-10-10"],[180,"2026-11-10"],[300,"2027-01-10"],[780,"2027-09-10"]] as const) {
 const r=buildBillingLedger([base,payment(amount)],now);
 assert.equal(r.coveredUntil.slice(0,10),coverage);
 assert.equal(r.payments.filter(p=>p.sourceOrderId==="one").length,amount/60);
}
assert.equal(buildBillingLedger([base,payment(120,"a","waiting"),payment(120,"b","waiting")],now).coveredUntil,base.dueAt);
assert.equal(buildBillingLedger([base,payment(120),payment(120)],now).coveredUntil.slice(0,10),"2026-10-10");
assert.equal(buildBillingLedger([base,payment(120,"a","confirmed")],now).coveredUntil,base.dueAt);
const part=buildBillingLedger([base,payment(90)],now);assert.equal(part.creditUsd,30);assert.equal(part.coveredUntil.slice(0,10),"2026-09-10");
assert.equal(buildBillingLedger([base,payment(90),payment(30,"two")],now).coveredUntil.slice(0,10),"2026-10-10");
assert.equal(buildBillingLedger([base,{...payment(120),manualReviewRequired:true}],now).coveredUntil,base.dueAt);
const overdue=buildBillingLedger([base],new Date("2026-11-09T00:00:00Z"));
assert.equal(overdue.payments.filter(p=>p.autoGenerated).reduce((s,p)=>s+p.amountUsd,0),180);
const adjusted=[base,{...base,orderId:"sep",dueAt:"2026-09-10T12:00:00.000Z"},{...base,orderId:"oct",dueAt:"2026-10-10T12:00:00.000Z"}];
assert.equal(buildBillingLedger([...adjusted,payment(60)],now).coveredUntil.slice(0,10),"2026-11-10");
const annual=buildBillingLedger([base,{...payment(600),billingMode:"anual"}],now);assert.equal(annual.coveredUntil.slice(0,10),"2027-08-10");
const p={payment_status:"finished",order_id:"test",price_amount:120, extra:{z:1,a:2},list:[{z:2,a:1}]};
const sig=createHmac("sha512","test").update(JSON.stringify(sortPaymentPayload(p))).digest("hex");
assert(verifyPaymentSignature(p,sig,"test"));assert(!verifyPaymentSignature({...p,price_amount:180},sig,"test"));assert(!verifyPaymentSignature(p,"bad","test"));assert(!verifyPaymentSignature(p,sig,""));
console.log("PASS: multi-month, overdue, advances, pending attempts, duplicate payments, partial credit, annual, historical adjustment and signatures");
