export const SERVER_PLANS = {
  starter: { mensual: 60, anual: 600 },
  pro: { mensual: 90, anual: 900 },
  elite: { mensual: 160, anual: 1250 },
} as const;
export type ServerPayment = {
  orderId: string; planId: keyof typeof SERVER_PLANS; billingMode: "mensual" | "anual";
  amountUsd: number; paymentStatus: string; createdAt: string; updatedAt: string;
  paidAt?: string; dueAt?: string; paymentId?: string | number; invoiceId?: string | number;
  invoiceUrl?: string; unitPriceUsd?: number; [key: string]: any;
};
export function addBillingMonths(value: string, months: number) {
  const d = new Date(value);
  const end = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + months + 1, 0)).getUTCDate();
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + months, Math.min(d.getUTCDate(), end), 12)).toISOString();
}
export function isSettled(status: string) {
  return ["finished", "paid"].includes(status.toLowerCase());
}
export function buildBillingLedger(orders: ServerPayment[], now = new Date()) {
  const rows: ServerPayment[] = [];
  const seen = new Set<string>();
  let coveredUntil = "2025-12-10T12:00:00.000Z";
  let lastPlan: keyof typeof SERVER_PLANS = "starter";
  let lastMode: "mensual" | "anual" = "mensual";
  const credit = new Map<string, number>();
  const paid = orders.filter(p => isSettled(p.paymentStatus) && !p.manualReviewRequired).sort((a, b) =>
    Number(Boolean(b.dueAt)) - Number(Boolean(a.dueAt)) ||
    (a.dueAt || a.paidAt || a.createdAt).localeCompare(b.dueAt || b.paidAt || b.createdAt) || a.orderId.localeCompare(b.orderId));
  for (const p of paid) {
    const key = p.paymentId ? `payment:${p.paymentId}` : `order:${p.orderId}`;
    if (seen.has(key)) continue;
    seen.add(key);
    if (p.dueAt) {
      rows.push({ ...p, periodAt: p.dueAt });
      if (p.dueAt > coveredUntil) coveredUntil = p.dueAt;
      lastPlan = p.planId; lastMode = p.billingMode;
      continue;
    }
    const price = p.unitPriceUsd || SERVER_PLANS[p.planId][p.billingMode];
    const bucket = `${p.planId}:${p.billingMode}:${price}`;
    const cents = Math.round(p.amountUsd * 100) + (credit.get(bucket) || 0);
    const unitCents = Math.round(price * 100);
    const count = Math.floor(cents / unitCents);
    credit.set(bucket, cents % unitCents);
    for (let i = 0; i < count; i++) {
      coveredUntil = addBillingMonths(coveredUntil, p.billingMode === "anual" ? 12 : 1);
      rows.push({ ...p, orderId: `${p.orderId}/cuota-${i + 1}`, sourceOrderId: p.orderId,
        amountUsd: price, dueAt: coveredUntil, periodAt: coveredUntil });
    }
    if (count) { lastPlan = p.planId; lastMode = p.billingMode; }
  }
  let cursor = coveredUntil;
  while (new Date(cursor).getTime() < now.getTime()) {
    cursor = addBillingMonths(cursor, lastMode === "anual" ? 12 : 1);
    rows.push({ orderId: `inv-${cursor.slice(0, 7)}`, planId: lastPlan, billingMode: lastMode,
      amountUsd: SERVER_PLANS[lastPlan][lastMode], paymentStatus: "waiting", autoGenerated: true,
      dueAt: cursor, periodAt: cursor, createdAt: cursor, updatedAt: cursor });
  }
  return { payments: rows, coveredUntil, creditUsd: Array.from(credit.values()).reduce((a, b) => a + b, 0) / 100 };
}
